export enum ActionKeyword {
  Play = "jouer",
  SelectBlind = "selectionner",
  Discard = "retirer",
  RearrangeHand = "arranger",
  RearrangeConsumables = "arrangerconso",
  RearrangeJokers = "arrangerjokers",
  SellConsumable = "vendreconso",
  SellJoker = "vendrejoker",
  SkipBlind = "passer",
  UseConsumable = "conso",
  BuyCard = "acheter",
  BuyVoucher = "achetercoupon",
  BuyPack = "acheterpack",
  PackSelect = "prendrepack",
  NextRound = "quitter",
  Reroll = "changer",
  StartRun = "commencer",
}

