export enum GameCycleState {
  MENU = "MENU",
  BLIND_SELECT = "BLIND_SELECT",
  SELECTING_HAND = "SELECTING_HAND",
  ROUND_EVAL = "ROUND_EVAL",
  SHOP = "SHOP",
  SMODS_BOOSTER_OPENED = "SMODS_BOOSTER_OPENED",
  GAME_OVER = "GAME_OVER",
}

